import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  containerSign: {
    padding: 0,
    flex: 1,
    marginTop: 50,
  },
  headingContainerSign: {
    alignItems: "center",
    paddingTop: 150,
  },
  headingContainerDiet: {
    alignItems: "center",
  },
  rectangle: {
    width: 327,
    height: 70,
    flexShrink: 0,
    backgroundColor: "rgba(28, 31, 34, 0.9)",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  rectangleType: {
    width: 280,
    height: 80,
    flexShrink: 0,
    backgroundColor: "#2E3138",
    borderBottomWidth: 5,
    borderLeftWidth: 5,
    borderTopWidth: 5,
    borderRightWidth: 5,
    borderRadius: 40,
    borderColor: "#5CBFF1",
    opacity: 0.9,
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  typeNme: {
    fontFamily: "Lato-Bold",
    color: "#ffffff",
    fontSize: 25,
  },
  rectangleSuggestion: {
    width: 350,
    height: 150,
    flexShrink: 0,
    backgroundColor: "#2E3138",
    borderBottomWidth: 5,
    borderLeftWidth: 5,
    borderRadius: 30,
    borderColor: "#6F46A9",
    opacity: 0.9,
    marginTop: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  dietExercisePlan: {
    fontFamily: "Lato-Bold",
    color: "#ffffff",
    fontSize: 25,
  },
  headingSign: {
    fontFamily: "Lato-Bold",
    color: "#FDFDFD",
    fontSize: 100,
    height: 150,
  },
  subheadingContainerSign: {
    alignItems: "center",
    paddingTop: 20,
    paddingBottom: 50,
  },
  subHeadingSign1: {
    fontFamily: "Lato-Bold",
    color: "#FFF",
    fontSize: 45,
  },
  subheadingContainerSign1: {
    alignItems: "center",
    paddingTop: 20,
    paddingBottom: 10,
  },
  subHeadingSign: {
    fontFamily: "Lato-Regular",
    color: "#000000",
    fontSize: 25,
  },
  buttonContainerSign1: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  ButtonSign1: {
    backgroundColor: "rgba(133, 79, 200, 0.8)",
    color: "white",
    padding: 10,
    borderRadius: 25,
    marginTop: 90,
    alignItems: "center",
    justifyContent: "center",
    width: 300,
    height: 70,
  },
  errorTextSign: {
    color: "red",
    fontSize: 14,
    marginTop: 5,
  },
  buttonTextSign1: {
    color: "#FDFDFD",
    fontSize: 25,
    fontFamily: "Lato-Bold",
  },
  buttonContainerSign2: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  ButtonSign2: {
    backgroundColor: "rgba(114, 0, 255, 0.8)",
    color: "white",
    padding: 10,
    borderRadius: 25,
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
    width: 300,
    height: 70,
  },
  buttonContainerExit: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  ButtonExit: {
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    color: "white",
    padding: 10,
    borderRadius: 25,
    marginTop: 40,
    alignItems: "center",
    justifyContent: "center",
    width: 300,
    height: 70,
    marginBottom: 20,
  },
  buttonTextSign2: {
    color: "#FDFDFD",
    fontSize: 25,
    fontFamily: "Lato-Bold",
  },
  backgroundContainerSign: {
    flex: 1,
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    alignItems: "center",
  },
  backgroundImageSign: {
    flex: 1,
    resizeMode: "contain",
    position: "absolute",
    top: 0,
    right: -20,
    alignItems: "center",
  },

  divideContainerSign: {
    alignItems: "center",
    paddingTop: 20,
  },
  divideSign: {
    fontFamily: "Lato-Bold",
    color: "#FDFDFD",
    fontSize: 30,
  },
  popupContainerSign: {
    backgroundColor: "#383b42",
    padding: 20,
    alignItems: "center",
    justifyContent: "top",
    borderRadius: 20,
    position: "absolute",
    height: "200",
    width: "100%",
    bottom: 0,
  },
  popupContainerSign1: {
    backgroundColor: "#383b42",
    padding: 20,
    alignItems: "center",
    justifyContent: "top",
    borderRadius: 20,
    position: "absolute",
    height: "200",
    width: "100%",
    bottom: 0,
  },
  popupSign: {
    padding: 20,
    borderRadius: 10,
    width: 300,
  },
  inputSign: {
    color: "white",
    fontFamily: "Lato-Regular",
    backgroundColor: "#2b2e34",
    borderRadius: 18,
    padding: 10,
    width: 327,
    alignSelf: "center",
    marginTop: 20,
    fontSize: 18,
  },
  popupButtonSign: {
    backgroundColor: "rgba(133, 79, 200, 0.8)",
    padding: 10,
    borderRadius: 25,
    alignItems: "center",
    width: 327,
    alignSelf: "center",
    marginTop: 30,
  },
  popupButtonTextSign: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  rectangleSign: {
    width: 200,
    height: 5,
    backgroundColor: "#000000",
    alignSelf: "center",
    marginTop: 5,
    marginBottom: 0,
    borderRadius: 5,
  },
  containerPredict: {
    backgroundColor: "#27292E",
    paddingTop: 100,
  },
  headingContainerPredict: {
    alignItems: "center",
    paddingTop: 50,
  },
  headingPredict: {
    fontFamily: "Lato-Bold",
    color: "white",
    alignItems: "center",
    fontSize: 25,
  },
  headingContainerUser: {
    alignItems: "center",
    paddingTop: 20,
    marginBottom: 20,
  },
  profileIcon: {
    alignItems: "center",
    marginBottom: 20,
  },
  headingUser: {
    fontFamily: "Lato-Bold",
    color: "white",
    alignItems: "center",
    fontSize: 50,
    marginBottom: 10,
  },
  subheadingContainerPredict: {
    alignItems: "center",
    paddingTop: 20,
    paddingBottom: 40,
  },
  subHeadingPredict: {
    fontFamily: "Lato-Regular",
    color: "#7F8489",
    fontSize: 12,
  },
  labelPredict: {
    color: "white",
    paddingTop: 5,
  },
  inputContainerPredict: {
    alignItems: "center",
    marginTop: 40,
    marginBottom: 20,
  },
  inputWrapperPredict: {
    marginBottom: 20,
  },
  inputPredict: {
    color: "white",
    fontFamily: "Lato-Regular",
    backgroundColor: "#2C3036",
    borderRadius: 18,
    padding: 10,
    width: 327,
    fontSize: 18,
  },
  inputWrapperUser: {
    marginBottom: 10,
    height: "200",
  },
  inputUser: {
    color: "#7F8489",
    fontFamily: "Lato-Regular",
    backgroundColor: "#2C3036",
    borderRadius: 18,
    padding: 10,
    width: 327,
    fontSize: 18,
  },
  inputLabel: {
    color: "white",
    fontFamily: "Lato-Regular",
    fontSize: 18,
    marginBottom: 5,
  },
  fieldName: {
    color: "white",
    fontFamily: "Lato-Regular",
    padding: 5,
  },
  buttonContainerPredict: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  predictButton: {
    backgroundColor: "#6F46A9",
    color: "white",
    fontSize: 18,
    padding: 10,
    borderRadius: 14,
    marginTop: 5,
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
    width: 327,
  },
  buttonTextPredict: {
    color: "white",
    fontSize: 18,
    fontFamily: "Lato-Bold",
  },
  errorPredict: {
    color: "red",
  },
  modalContainerPredict: {
    backgroundColor: "#27292E",
    padding: 20,
    alignItems: "center",
    justifyContent: "top",
    borderRadius: 20,
    position: "absolute",
    height: "45%",
    width: "100%",
    bottom: 0,
  },
  modalPossibility: {
    color: "white",
    fontSize: 45,
    fontFamily: "Lato-Bold",
  },
  modalType: {
    color: "white",
    fontSize: 30,
    fontFamily: "Lato-Bold",
    marginTop: 5,
  },
  modalButtonContainerCancelPredict: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 20,
    width: 300,
    height: 60,
    borderRadius: 18,
    backgroundColor: "#2D3338",
    alignItems: "center",
  },
  modalButtonCancel: {
    color: "#ffffff",
    fontSize: 30,
    fontFamily: "Lato-Regular",
  },
  modalButtonContainerNextPredict: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 50,
    width: 300,
    height: 60,
    borderRadius: 18,
    backgroundColor: "#2D3338",
    alignItems: "center",
    marginTop: 40,
  },
  modalButtonNextPredict: {
    color: "#ffffff",
    fontSize: 30,
    fontFamily: "Lato-Regular",
  },
  circleButtonContainerPredict: {
    position: "absolute",
    top: 80,
    left: 20,
    zIndex: 1,
  },
  circleButtonPredict: {
    width: 60,
    height: 55,
    borderRadius: 25,
    backgroundColor: "#2D3338",
    justifyContent: "center",
    alignItems: "center",
  },
  circleButtonImagePredict: {
    width: 24,
    height: 24,
    resizeMode: "contain",
  },
  rectanglePredict: {
    width: 200,
    height: 5,
    backgroundColor: "#000000",
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 40,
    borderRadius: 5,
  },
  headingContainerType: {
    alignItems: "center",
    paddingTop: 60,
  },
  subheadingContainerType: {
    alignItems: "center",
    paddingTop: 20,
  },
  genderPicker: {
    color: "#7F8489",
    fontFamily: "Lato-Regular",
    backgroundColor: "#2C3036",
    borderRadius: 18,
    width: 327,
    fontSize: 18,
  },
  genderPickerContainer: {
    color: "#7F8489",
    fontFamily: "Lato-Regular",
    backgroundColor: "#2C3036",
    borderRadius: 18,
    overflow: "hidden",
  },
});
